language: python
python:
  - "3.7"
# command to install dependencies
env:
  global:
    - ENVIRONMENT ='development'
# command to install dependencies
install:
  - pip install -r requirements.txt
# db configurations
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE vtenderapi;" -U postgres
  - psql -c "CREATE USER vtendertestuser WITH PASSWORD '1234';" -U postgres
# command to run tests
script:
  - pytest