language: python
python:
  - "3.7"
# command to install dependencies
env:
  global:
    APP_SETTINGS ='development'
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# db configurations
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE vtenderapi;" -U postgres
  - psql -c "CREATE USER vtendertestuser WITH PASSWORD '1234';" -U postgres
# command to run tests
script:
  - pytest

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  provider: heroku
  app: vtender
  strategy: git
  api_key: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTE2OTE5NTEsImlhdCI6MTU5MTUxMTk1MSwic3ViIjoyfQ.7E64mm8rGLwWMXQouubzxX2k2aiWa3ZcA9w8F7fGVLo"