"""
empty message

Revision ID: c1b09bd9172a
Revises: ''
Create Date: 2020-05-17 19:31:44.331203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b09bd9172a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tenderNumber', sa.String(length=25), nullable=True),
    sa.Column('tenderDescription', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('datePublished', sa.String(length=15), nullable=True),
    sa.Column('closingDate', sa.String(length=15), nullable=True),
    sa.Column('tenderStatus', sa.String(length=10), nullable=True),
    sa.Column('nameOfInstitution', sa.String(length=25), nullable=True),
    sa.Column('officalLocation', sa.String(length=25), nullable=True),
    sa.Column('InstitutionContactPerson', sa.String(length=25), nullable=True),
    sa.Column('InstitutionPersonEmail', sa.String(length=25), nullable=True),
    sa.Column('InstitutionPersonPhone', sa.String(length=15), nullable=True),
    sa.Column('companyName', sa.String(length=40), nullable=True),
    sa.Column('companyRegistrationNo', sa.String(length=30), nullable=True),
    sa.Column('directors', sa.String(length=50), nullable=True),
    sa.Column('cellNumber', sa.String(length=15), nullable=True),
    sa.Column('companyAddress', sa.String(length=50), nullable=True),
    sa.Column('awardedPoint', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('tender_id'),
    sa.UniqueConstraint('tenderNumber')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('tender')
    # ### end Alembic commands ###
